---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: dotnet-microservice
spec:
    replicas: 1
    selector:
      matchLabels:
        app: dotnet-microservice
    template:
      metadata:
        labels:
          app: dotnet-microservice
      spec:
        containers:
        - name: dotnet-microservice
          image: xolisamatika/mymicroservice:latest
          ports:
          - containerPort: 80
          env:
          - name: ASPNETCORE_URLS
            value: http://*:80
---
apiVersion: v1
kind: Service
metadata:
    name: dotnet-microservice
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
      app: dotnet-microservice